name: moving_tags
description: Automatically move your GitHub Action tags on release.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  args: ^2.3.0
  shell: ^2.0.0
  version: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
