name: tagger
description: Automatically move your GitHub Action tags on release.
version: 0.0.1
repository: https://github.com/fischerscode/tagger

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  shell: ^2.0.0
  version: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
